app:
  name: "bot-mgmt-server"
  env: "dev"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "bot_db"

logger:
  level: "debug"
  format: "console" # Easier to read in dev


aws:
  region: "ap-northeast-2"
  profile: "bot-mgmt"

ecs:
  cluster: "default"
  task_def: "bot-task"
  container_name: "bot-container"
  subnets: 

    - "subnet-xxxx"
    - "subnet-yyyy"
  sec_group: "sg-xxxx"

task:
  max_retries: 3


server:
  http:
    port: 8080
